import type { Lang } from "@/lib/dashLang";

// Static (non-computed) strings for the BOD PDF (bodReportPdf.tsx). The
// narrative/insight SENTENCES (which interpolate numbers into full
// sentences) are generated by language-specific functions further down
// rather than a flat dictionary — EN and JP restructure those sentences
// rather than substituting words 1:1 into the Indonesian word order.
export function tf(str: string, vars: Record<string, string | number>): string {
  return str.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ""));
}

const id = {
  cover_kicker: "PANASONIC E-COMMERCE PERFORMANCE",
  cover_reportLine: "LAPORAN PERFORMA BULANAN",
  cover_focusBrand: "Fokus Brand: Panasonic",
  cover_preparedFor: "Disiapkan untuk:  Panasonic — Board of Directors",
  cover_channel: "Kanal:  Shopee   ·   Program Dealer E-Commerce",
  cover_generated: "Dibuat {date}",

  sec1_title: "Ringkasan Eksekutif",
  sec2_title: "Dampak Program Reline — Sebelum vs Sesudah",
  sec3_title: "Tren & Komposisi",
  sec4_title: "Performa Dealer — {n} dealer",
  sec5_title: "10 Produk Terlaris — {period}",
  sec6_title: "Makna & Langkah Selanjutnya",

  summaryLabel: "RINGKASAN",

  kpi_sales: "PENJUALAN PANASONIC · SIAP DIKIRIM", kpi_salesSub: "SPOS · parent row",
  kpi_traffic: "TRAFIK PRODUK", kpi_trafficSub: "Pengunjung produk",
  kpi_inCart: "TAMBAH KE KERANJANG", kpi_inCartSub: "Rasio ATC {pct}",
  kpi_adsCost: "BIAYA IKLAN", kpi_adsCostSub: "Panasonic · Ads",
  kpi_roas: "ROAS · SALES ÷ BIAYA", kpi_roasSub: "Dari {rp} belanja iklan",
  kpi_gmv: "TOTAL TOKO · SEMUA BRAND", kpi_gmvSub: "Pangsa Panasonic: {pct}",

  p3_salesTitle: "Performa Penjualan Panasonic", p3_salesSub: "Penjualan siap dikirim · {n} periode terakhir",
  p3_costRoasTitle: "Biaya Iklan & ROAS", p3_costRoasSub: "Biaya vs efisiensi · {n} periode terakhir",
  p3_funnelTitle: "Funnel Konversi", p3_funnelSub: "Trafik → keranjang · {period}",
  p3_traffic: "Trafik", p3_cart: "Keranjang", p3_cartNote: "({pct} dari trafik)",
  p3_shareTitle: "Pangsa Toko", p3_shareSub: "Panasonic vs brand lain (pendapatan)",
  p3_legendPana: "Panasonic — {v}", p3_legendOther: "Brand lain — {v}",

  p4_no: "#", p4_dealer: "DEALER", p4_city: "KOTA", p4_sales: "PENJUALAN", p4_traffic: "TRAFIK",
  p4_cart: "KERANJANG", p4_adsCost: "BIAYA IKLAN", p4_roas: "ROAS",
  p4_empty: "Tidak ada data dealer untuk filter ini.",
  p4_overflow: "Menampilkan 11 dealer teratas dari {n}. Total penjualan seluruh dealer: {v}.",

  p5_no: "#", p5_product: "PRODUK", p5_sales: "PENJUALAN", p5_panaPct: "% PANA.",
  p5_empty: "Tidak ada data produk untuk filter ini.",

  p2_noBaselineTitle: 'Data baseline ("Month Awal") belum tersedia',
  p2_noBaselineNote: 'Perbandingan sebelum-vs-sesudah membutuhkan data "Month Awal" untuk cakupan yang dipilih.',
  p2_rowSales: "Penjualan Panasonic (total)", p2_rowAds: "Biaya iklan (total)", p2_rowRoas: "ROAS (total periode)", p2_rowCoverage: "Cakupan data",
  p2_noManagedAds: "tanpa iklan terkelola", p2_newProgram: "program baru",
  p2_perMonth: " / bulan", p2_storesMonthAwal: "{n} toko (Month Awal)", p2_monthsActive: "{n} bulan aktif",
  p2_th_metric: "METRIK", p2_th_before: "SEBELUM", p2_th_after: "SESUDAH", p2_th_change: "PERUBAHAN",
  p2_detailLabel: "RINCIAN SEBELUM — SESUDAH   (total cakupan, rata-rata per bulan)",
  p2_bigSales: "Penjualan Panasonic", p2_bigAds: "Biaya Iklan (investasi)",
  p2_roasActiveLabel: "ROAS PROGRAM AKTIF", p2_roasBefore: "Sebelumnya {v}", p2_roasNoAdsBefore: "Sebelumnya tidak ada iklan terkelola",
  p2_footnote: 'Catatan: "Sebelum" adalah total snapshot Month Awal (pra-program) dari {stores} toko; "Sesudah" adalah total seluruh cakupan dibagi rata-rata per bulan selama {months} bulan aktif. Keduanya adalah total cakupan (kota/dealer terpilih), bukan dibagi jumlah toko.{adsThinNote}',
  p2_adsThinNote: " Sebelum program, belanja iklan hampir nol sehingga ROAS pra-program bukan rasio yang bermakna untuk dibandingkan.",

  tone_win: "MENANG", tone_insight: "INSIGHT", tone_watch: "PERHATIAN",
  p6_actionsLabel: "REKOMENDASI AKSI — PERIODE BERIKUTNYA",

  footL: "Reline · Panasonic E-Commerce Dealer Program",
  footR: "Sumber: dashboard Reline (SPOS · Performa · Ads) · ROAS = Penjualan Panasonic ÷ Biaya Iklan",
  chartEmpty: "Data tidak tersedia untuk filter ini",
  donutPanasonic: "Panasonic",
  scopeAllDealers: "Seluruh Dealer Panasonic",
  scopeAllPeriod: "Seluruh Periode",
};

const en = {
  cover_kicker: "PANASONIC E-COMMERCE PERFORMANCE",
  cover_reportLine: "MONTHLY PERFORMANCE REPORT",
  cover_focusBrand: "Brand Focus: Panasonic",
  cover_preparedFor: "Prepared for:  Panasonic — Board of Directors",
  cover_channel: "Channel:  Shopee   ·   E-Commerce Dealer Program",
  cover_generated: "Generated {date}",

  sec1_title: "Executive Summary",
  sec2_title: "Reline Program Impact — Before vs After",
  sec3_title: "Trends & Composition",
  sec4_title: "Dealer Performance — {n} dealers",
  sec5_title: "Top 10 Best-Selling Products — {period}",
  sec6_title: "Insights & Next Steps",

  summaryLabel: "SUMMARY",

  kpi_sales: "PANASONIC SALES · READY TO SHIP", kpi_salesSub: "SPOS · parent row",
  kpi_traffic: "PRODUCT TRAFFIC", kpi_trafficSub: "Product visitors",
  kpi_inCart: "ADDED TO CART", kpi_inCartSub: "ATC rate {pct}",
  kpi_adsCost: "AD SPEND", kpi_adsCostSub: "Panasonic · Ads",
  kpi_roas: "ROAS · SALES ÷ SPEND", kpi_roasSub: "From {rp} ad spend",
  kpi_gmv: "TOTAL STORE SALES · ALL BRANDS", kpi_gmvSub: "Panasonic share: {pct}",

  p3_salesTitle: "Panasonic Sales Performance", p3_salesSub: "Ready-to-ship sales · last {n} periods",
  p3_costRoasTitle: "Ad Spend & ROAS", p3_costRoasSub: "Spend vs efficiency · last {n} periods",
  p3_funnelTitle: "Conversion Funnel", p3_funnelSub: "Traffic → cart · {period}",
  p3_traffic: "Traffic", p3_cart: "Cart", p3_cartNote: "({pct} of traffic)",
  p3_shareTitle: "Store Share", p3_shareSub: "Panasonic vs other brands (revenue)",
  p3_legendPana: "Panasonic — {v}", p3_legendOther: "Other brands — {v}",

  p4_no: "#", p4_dealer: "DEALER", p4_city: "CITY", p4_sales: "SALES", p4_traffic: "TRAFFIC",
  p4_cart: "CART", p4_adsCost: "AD SPEND", p4_roas: "ROAS",
  p4_empty: "No dealer data for this filter.",
  p4_overflow: "Showing the top 11 of {n} dealers. Total sales across all dealers: {v}.",

  p5_no: "#", p5_product: "PRODUCT", p5_sales: "SALES", p5_panaPct: "% OF PANA.",
  p5_empty: "No product data for this filter.",

  p2_noBaselineTitle: 'Baseline ("Starting Month") data not yet available',
  p2_noBaselineNote: 'A before-vs-after comparison needs "Starting Month" data for the selected scope.',
  p2_rowSales: "Panasonic sales (total)", p2_rowAds: "Ad spend (total)", p2_rowRoas: "ROAS (whole period)", p2_rowCoverage: "Data coverage",
  p2_noManagedAds: "no managed ads", p2_newProgram: "new program",
  p2_perMonth: " / month", p2_storesMonthAwal: "{n} stores (Starting Month)", p2_monthsActive: "{n} active months",
  p2_th_metric: "METRIC", p2_th_before: "BEFORE", p2_th_after: "AFTER", p2_th_change: "CHANGE",
  p2_detailLabel: "BEFORE — AFTER BREAKDOWN   (total coverage, monthly average)",
  p2_bigSales: "Panasonic Sales", p2_bigAds: "Ad Spend (investment)",
  p2_roasActiveLabel: "ACTIVE PROGRAM ROAS", p2_roasBefore: "Previously {v}", p2_roasNoAdsBefore: "No managed ads before this",
  p2_footnote: '"Before" is the total pre-project "Starting Month" snapshot from {stores} stores; "After" is the total across the full coverage divided by the average across {months} active months. Both are totals for the selected scope (city/dealer), not divided by store count.{adsThinNote}',
  p2_adsThinNote: " Before the program, ad spend was near zero, so the pre-program ROAS is not a meaningful ratio to compare.",

  tone_win: "WIN", tone_insight: "INSIGHT", tone_watch: "WATCH",
  p6_actionsLabel: "RECOMMENDED ACTIONS — NEXT PERIOD",

  footL: "Reline · Panasonic E-Commerce Dealer Program",
  footR: "Source: Reline dashboard (SPOS · Store Performance · Ads) · ROAS = Panasonic Sales ÷ Ad Spend",
  chartEmpty: "No data available for this filter",
  donutPanasonic: "Panasonic",
  scopeAllDealers: "All Panasonic Dealers",
  scopeAllPeriod: "All Periods",
} satisfies Record<keyof typeof id, string>;

const jp = {
  cover_kicker: "パナソニック Eコマース実績",
  cover_reportLine: "月次実績報告書",
  cover_focusBrand: "対象ブランド：パナソニック",
  cover_preparedFor: "提出先：パナソニック — 取締役会",
  cover_channel: "チャネル：Shopee　・　Eコマース販売店プログラム",
  cover_generated: "作成日 {date}",

  sec1_title: "エグゼクティブサマリー",
  sec2_title: "Relineプログラムの効果 — 導入前後比較",
  sec3_title: "トレンドと構成",
  sec4_title: "販売店別実績 — {n}店舗",
  sec5_title: "売上トップ10製品 — {period}",
  sec6_title: "考察と次のアクション",

  summaryLabel: "サマリー",

  kpi_sales: "パナソニック売上・出荷準備完了", kpi_salesSub: "SPOS・親行のみ",
  kpi_traffic: "商品トラフィック", kpi_trafficSub: "商品訪問者数",
  kpi_inCart: "カート追加数", kpi_inCartSub: "カート追加率 {pct}",
  kpi_adsCost: "広告費", kpi_adsCostSub: "パナソニック・広告",
  kpi_roas: "ROAS・売上 ÷ 広告費", kpi_roasSub: "広告費 {rp} に対して",
  kpi_gmv: "店舗総売上・全ブランド", kpi_gmvSub: "パナソニックシェア：{pct}",

  p3_salesTitle: "パナソニック売上実績", p3_salesSub: "出荷準備完了売上・直近{n}期間",
  p3_costRoasTitle: "広告費とROAS", p3_costRoasSub: "費用対効果・直近{n}期間",
  p3_funnelTitle: "コンバージョンファネル", p3_funnelSub: "トラフィック → カート追加・{period}",
  p3_traffic: "トラフィック", p3_cart: "カート追加", p3_cartNote: "（トラフィックの{pct}）",
  p3_shareTitle: "店舗内シェア", p3_shareSub: "パナソニック vs 他ブランド（売上高）",
  p3_legendPana: "パナソニック — {v}", p3_legendOther: "他ブランド — {v}",

  p4_no: "#", p4_dealer: "販売店", p4_city: "都市", p4_sales: "売上", p4_traffic: "トラフィック",
  p4_cart: "カート追加", p4_adsCost: "広告費", p4_roas: "ROAS",
  p4_empty: "このフィルターに該当する販売店データがありません。",
  p4_overflow: "全{n}店舗中、上位11店舗を表示しています。全販売店の売上合計：{v}。",

  p5_no: "#", p5_product: "製品", p5_sales: "売上", p5_panaPct: "パナ比率",
  p5_empty: "このフィルターに該当する製品データがありません。",

  p2_noBaselineTitle: "ベースライン（「開始月」）データがまだありません",
  p2_noBaselineNote: "導入前後比較には、対象範囲の「開始月」データが必要です。",
  p2_rowSales: "パナソニック売上（合計）", p2_rowAds: "広告費（合計）", p2_rowRoas: "ROAS（全期間）", p2_rowCoverage: "データ対象期間",
  p2_noManagedAds: "広告施策なし", p2_newProgram: "新規プログラム",
  p2_perMonth: "／月", p2_storesMonthAwal: "{n}店舗（開始月）", p2_monthsActive: "稼働{n}か月",
  p2_th_metric: "指標", p2_th_before: "導入前", p2_th_after: "導入後", p2_th_change: "変化",
  p2_detailLabel: "導入前後の内訳　（対象範囲合計、月平均）",
  p2_bigSales: "パナソニック売上", p2_bigAds: "広告費（投資額）",
  p2_roasActiveLabel: "稼働中プログラムのROAS", p2_roasBefore: "導入前：{v}", p2_roasNoAdsBefore: "導入前は広告施策なし",
  p2_footnote: "注記：「導入前」は{stores}店舗のプロジェクト開始前（開始月）スナップショットの合計、「導入後」は対象範囲全体の合計を稼働{months}か月の平均で示したものです。いずれも対象範囲（選択した都市・販売店）の合計であり、店舗数で割った値ではありません。{adsThinNote}",
  p2_adsThinNote: "導入前は広告費がほぼゼロであったため、導入前のROASは比較対象として意味のある数値ではありません。",

  tone_win: "好調", tone_insight: "インサイト", tone_watch: "要注意",
  p6_actionsLabel: "推奨アクション — 次期に向けて",

  footL: "Reline・パナソニック Eコマース販売店プログラム",
  footR: "出典：Relineダッシュボード（SPOS・店舗実績・広告）・ROAS = パナソニック売上 ÷ 広告費",
  chartEmpty: "このフィルターに該当するデータがありません",
  donutPanasonic: "パナソニック",
  scopeAllDealers: "全パナソニック販売店",
  scopeAllPeriod: "全期間",
} satisfies Record<keyof typeof id, string>;

export const BOD_T: Record<Lang, typeof id> = { id, en, jp };

/* ============ narrative generators (full sentences, not word-swaps) ============ */

type Kpis = { sales: number; gmv: number; traffic: number; in_cart: number; ad_cost: number; roas: number | null };

export function buildNarrative(
  lang: Lang, cur: Kpis, prev: Kpis | null, periodLabel: string, scopeLabel: string,
  fmt: { rp: (n: number) => string; pct: (n: number) => string; roasFmt: (n: number | null | undefined) => string; cnt: (n: number) => string },
  pctDelta: (cur: number, prev: number | null | undefined) => number | null,
): string {
  const dSales = pctDelta(cur.sales, prev?.sales);
  const dAds = pctDelta(cur.ad_cost, prev?.ad_cost);
  const share = cur.gmv > 0 ? (cur.sales / cur.gmv) * 100 : null;
  const atc = cur.traffic > 0 ? (cur.in_cart / cur.traffic) * 100 : 0;
  const { rp, pct, roasFmt, cnt } = fmt;

  if (lang === "en") {
    const parts: string[] = [];
    parts.push(`In ${periodLabel}, Panasonic sales in ${scopeLabel} reached ${rp(cur.sales)}${dSales != null ? ` — ${dSales >= 0 ? "up" : "down"} ${pct(Math.abs(dSales))} vs the prior period` : ""}.`);
    if (dAds != null && dSales != null) {
      parts.push(dAds < 0 && dSales > 0
        ? `This growth was efficient: ad spend actually fell ${pct(Math.abs(dAds))} to ${rp(cur.ad_cost)}, putting ROAS at ${roasFmt(cur.roas)}.`
        : `Ad spend ${dAds >= 0 ? "rose" : "fell"} ${pct(Math.abs(dAds))} to ${rp(cur.ad_cost)}, with ROAS at ${roasFmt(cur.roas)}.`);
    } else {
      parts.push(`Ad spend was ${rp(cur.ad_cost)} with ROAS at ${roasFmt(cur.roas)}.`);
    }
    parts.push(`The funnel logged ${cnt(cur.traffic)} product visits and ${cnt(cur.in_cart)} add-to-carts (a ${pct(atc)} ratio).`);
    if (share != null) parts.push(`Panasonic accounted for ${pct(share)} of total dealer store sales (${rp(cur.gmv)}).`);
    return parts.join(" ");
  }
  if (lang === "jp") {
    const parts: string[] = [];
    parts.push(`${periodLabel}、${scopeLabel}におけるパナソニックの売上は${rp(cur.sales)}に達し${dSales != null ? `、前期比${dSales >= 0 ? "増加" : "減少"}${pct(Math.abs(dSales))}となりました` : "ました"}。`);
    if (dAds != null && dSales != null) {
      parts.push(dAds < 0 && dSales > 0
        ? `この成長は効率的なもので、広告費はむしろ${pct(Math.abs(dAds))}減少して${rp(cur.ad_cost)}となり、ROASは${roasFmt(cur.roas)}となりました。`
        : `広告費は${pct(Math.abs(dAds))}${dAds >= 0 ? "増加" : "減少"}して${rp(cur.ad_cost)}となり、ROASは${roasFmt(cur.roas)}です。`);
    } else {
      parts.push(`広告費は${rp(cur.ad_cost)}、ROASは${roasFmt(cur.roas)}でした。`);
    }
    parts.push(`ファネルでは${cnt(cur.traffic)}件の商品訪問と${cnt(cur.in_cart)}件のカート追加を記録しました（比率${pct(atc)}）。`);
    if (share != null) parts.push(`パナソニックは販売店の総売上（${rp(cur.gmv)}）のうち${pct(share)}を占めています。`);
    return parts.join("");
  }
  // id (default)
  const parts: string[] = [];
  parts.push(`Pada ${periodLabel}, penjualan Panasonic di ${scopeLabel} mencapai ${rp(cur.sales)}${dSales != null ? ` — ${dSales >= 0 ? "naik" : "turun"} ${pct(Math.abs(dSales))} dibanding periode sebelumnya` : ""}.`);
  if (dAds != null && dSales != null) {
    parts.push(dAds < 0 && dSales > 0
      ? `Pertumbuhan ini efisien: biaya iklan justru turun ${pct(Math.abs(dAds))} menjadi ${rp(cur.ad_cost)}, sehingga ROAS berada di ${roasFmt(cur.roas)}.`
      : `Biaya iklan ${dAds >= 0 ? "naik" : "turun"} ${pct(Math.abs(dAds))} menjadi ${rp(cur.ad_cost)}, dengan ROAS ${roasFmt(cur.roas)}.`);
  } else {
    parts.push(`Biaya iklan tercatat ${rp(cur.ad_cost)} dengan ROAS ${roasFmt(cur.roas)}.`);
  }
  parts.push(`Funnel mencatat ${cnt(cur.traffic)} kunjungan produk dan ${cnt(cur.in_cart)} tambah-ke-keranjang (rasio ${pct(atc)}).`);
  if (share != null) parts.push(`Panasonic menyumbang ${pct(share)} dari total penjualan toko dealer (${rp(cur.gmv)}).`);
  return parts.join(" ");
}

export type InsightCardData = { tone: "win" | "insight" | "watch"; title: string; body: string };

export function buildInsightCards(
  lang: Lang, dSales: number | null, dAds: number | null, dGmv: number | null,
  k: Kpis, atcRate: number, shareFrac: number, dealersLen: number, weak: number,
  fmt: { rp: (n: number) => string; pct: (n: number) => string; roasFmt: (n: number | null | undefined) => string; cnt: (n: number) => string },
): InsightCardData[] {
  const { rp, pct, roasFmt, cnt } = fmt;
  const cards: InsightCardData[] = [];

  if (lang === "en") {
    if (dSales != null && dAds != null && dSales > 0 && dAds < 0) {
      cards.push({ tone: "win", title: "Sales up, spend down", body: `Sales grew ${pct(dSales)} while ad spend fell ${pct(Math.abs(dAds))}. Demand is becoming more organic and the ad budget is working more efficiently — ROAS at ${roasFmt(k.roas)}.` });
    } else if (dSales != null && dSales > 0) {
      cards.push({ tone: "win", title: "Sales growing", body: `Panasonic sales rose ${pct(dSales)} to ${rp(k.sales)}, with ROAS at ${roasFmt(k.roas)}.` });
    } else {
      cards.push({ tone: "watch", title: "Sales not yet growing", body: `Panasonic sales at ${rp(k.sales)}${dSales != null ? ` (${pct(dSales)} vs prior period)` : ""}. Worth tracing the driver at the dealer and SKU level.` });
    }
    cards.push(atcRate >= 5
      ? { tone: "insight", title: "Top-of-funnel is healthy", body: `Add-to-cart ratio is ${pct(atcRate)} from ${cnt(k.traffic)} visits — interest is strengthening ahead of checkout.` }
      : { tone: "watch", title: "Top-of-funnel is thin", body: `Add-to-cart ratio is only ${pct(atcRate)} from ${cnt(k.traffic)} visits — worth checking traffic quality or listing relevance.` });
    cards.push(dGmv != null && dSales != null && dGmv > dSales
      ? { tone: "watch", title: "Share slipped despite growth", body: `Total dealer store sales grew faster (${pct(dGmv)}) than Panasonic (${pct(dSales)}), putting Panasonic's share at ${pct(shareFrac * 100)}. Other brands grew more — worth checking why.` }
      : { tone: "insight", title: `Panasonic share ${pct(shareFrac * 100)}`, body: `Panasonic accounted for ${pct(shareFrac * 100)} of total dealer store sales (${rp(k.gmv)}) this period.` });
    cards.push(weak > 0
      ? { tone: "watch", title: `${weak} dealers with ROAS below 1x`, body: `Of ${dealersLen} dealers, ${weak} spent more on ads than the Panasonic sales they generated. Prioritize support for these dealers.` }
      : { tone: "win", title: "Every dealer above 1x ROAS", body: `All ${dealersLen} dealers generated more Panasonic sales than ad spend this period.` });
    return cards;
  }
  if (lang === "jp") {
    if (dSales != null && dAds != null && dSales > 0 && dAds < 0) {
      cards.push({ tone: "win", title: "売上増加・広告費減少", body: `売上は${pct(dSales)}増加した一方、広告費は${pct(Math.abs(dAds))}減少しました。需要のオーガニック化が進み、広告予算がより効率的に機能しています — ROAS ${roasFmt(k.roas)}。` });
    } else if (dSales != null && dSales > 0) {
      cards.push({ tone: "win", title: "売上が成長", body: `パナソニックの売上は${pct(dSales)}増加し${rp(k.sales)}に達しました（ROAS ${roasFmt(k.roas)}）。` });
    } else {
      cards.push({ tone: "watch", title: "売上がまだ伸びていません", body: `パナソニックの売上は${rp(k.sales)}${dSales != null ? `（前期比${pct(dSales)}）` : ""}。販売店・SKUレベルでの要因分析が必要です。` });
    }
    cards.push(atcRate >= 5
      ? { tone: "insight", title: "ファネル上部は良好", body: `${cnt(k.traffic)}件の訪問に対しカート追加率は${pct(atcRate)}。チェックアウト前の関心が高まっています。` }
      : { tone: "watch", title: "ファネル上部が弱い", body: `${cnt(k.traffic)}件の訪問に対しカート追加率はわずか${pct(atcRate)}。トラフィックの質や商品情報の関連性を確認する必要があります。` });
    cards.push(dGmv != null && dSales != null && dGmv > dSales
      ? { tone: "watch", title: "成長はしているがシェアは低下", body: `販売店全体の売上（${pct(dGmv)}増）はパナソニック（${pct(dSales)}増）より速く伸びており、パナソニックのシェアは${pct(shareFrac * 100)}となりました。他ブランドの伸びが大きいため要因確認が必要です。` }
      : { tone: "insight", title: `パナソニックのシェア ${pct(shareFrac * 100)}`, body: `今期、パナソニックは販売店の総売上（${rp(k.gmv)}）のうち${pct(shareFrac * 100)}を占めました。` });
    cards.push(weak > 0
      ? { tone: "watch", title: `ROAS 1倍未満の販売店 ${weak}店`, body: `${dealersLen}店舗中${weak}店舗で、広告費がパナソニック売上を上回りました。これらの販売店への支援を優先してください。` }
      : { tone: "win", title: "全販売店でROAS 1倍超", body: `今期、全${dealersLen}店舗でパナソニック売上が広告費を上回りました。` });
    return cards;
  }
  // id
  if (dSales != null && dAds != null && dSales > 0 && dAds < 0) {
    cards.push({ tone: "win", title: "Sales naik, biaya turun", body: `Penjualan naik ${pct(dSales)} sementara biaya iklan turun ${pct(Math.abs(dAds))}. Permintaan makin organik dan anggaran iklan bekerja lebih efisien — ROAS di ${roasFmt(k.roas)}.` });
  } else if (dSales != null && dSales > 0) {
    cards.push({ tone: "win", title: "Penjualan tumbuh", body: `Penjualan Panasonic naik ${pct(dSales)} menjadi ${rp(k.sales)} dengan ROAS ${roasFmt(k.roas)}.` });
  } else {
    cards.push({ tone: "watch", title: "Penjualan belum tumbuh", body: `Penjualan Panasonic ${rp(k.sales)}${dSales != null ? ` (${pct(dSales)} vs periode sebelumnya)` : ""}. Perlu penelusuran pemicu di level dealer dan SKU.` });
  }
  cards.push(atcRate >= 5
    ? { tone: "insight", title: "Funnel atas sehat", body: `Rasio tambah-ke-keranjang ${pct(atcRate)} dari ${cnt(k.traffic)} kunjungan. Minat menguat sebelum tahap checkout.` }
    : { tone: "watch", title: "Funnel atas tipis", body: `Rasio tambah-ke-keranjang hanya ${pct(atcRate)} dari ${cnt(k.traffic)} kunjungan — kualitas trafik atau relevansi listing perlu dicek.` });
  cards.push(dGmv != null && dSales != null && dGmv > dSales
    ? { tone: "watch", title: "Pangsa turun meski tumbuh", body: `Total toko dealer tumbuh lebih cepat (${pct(dGmv)}) dari Panasonic (${pct(dSales)}), sehingga pangsa Panasonic di ${pct(shareFrac * 100)}. Brand lain tumbuh lebih besar — perlu dicek pemicunya.` }
    : { tone: "insight", title: `Pangsa Panasonic ${pct(shareFrac * 100)}`, body: `Panasonic menyumbang ${pct(shareFrac * 100)} dari total penjualan toko dealer (${rp(k.gmv)}) pada periode ini.` });
  cards.push(weak > 0
    ? { tone: "watch", title: `${weak} dealer dengan ROAS di bawah 1x`, body: `Dari ${dealersLen} dealer, ${weak} membelanjakan iklan lebih besar dari penjualan Panasonic yang dihasilkan. Prioritaskan pendampingan di dealer ini.` }
    : { tone: "win", title: "Semua dealer ROAS di atas 1x", body: `Seluruh ${dealersLen} dealer menghasilkan penjualan Panasonic melebihi belanja iklannya pada periode ini.` });
  return cards;
}

export function buildActions(lang: Lang, weak: number, cnt: (n: number) => string, inCart: number): string[] {
  if (lang === "en") {
    return [
      "Protect efficiency — maintain / scale ad budget on dealers & SKUs proven to run above target ROAS.",
      `Close the cart gap — activate checkout vouchers & follow-up chat on ${cnt(inCart)} carts from this period.`,
      "Push the premium mix — feature Inverter and premium-series models to raise average order value.",
      weak > 0 ? `Support the ${weak} low-ROAS dealers — audit ad structure and pricing before adding budget.` : "Replicate the best-performing dealer's playbook with other dealers in the same city.",
    ];
  }
  if (lang === "jp") {
    return [
      "効率を維持 — 目標ROASを上回っている販売店・SKUの広告予算を維持・拡大する。",
      `カート離脱を減らす — 今期の${cnt(inCart)}件のカート追加に対し、チェックアウトクーポンやフォローアップチャットを実施する。`,
      "プレミアムミックスを強化 — インバーターおよびプレミアムシリーズを訴求し、平均注文単価を引き上げる。",
      weak > 0 ? `低ROASの${weak}店舗を支援 — 予算追加の前に広告構成と価格を見直す。` : "好調な販売店の施策を同一都市の他店舗に展開する。",
    ];
  }
  return [
    "Jaga efisiensi — pertahankan / scale anggaran iklan pada dealer & SKU yang terbukti selama ROAS di atas target.",
    `Tutup jeda keranjang — aktifkan voucher checkout & follow-up chat pada ${cnt(inCart)} keranjang periode ini.`,
    "Dorong mix premium — tonjolkan model Inverter & seri premium untuk menaikkan nilai pesanan rata-rata.",
    weak > 0 ? `Dampingi ${weak} dealer ber-ROAS rendah — audit struktur iklan dan harga sebelum menambah anggaran.` : "Replikasi pola dealer terbaik ke dealer lain di kota yang sama.",
  ];
}

export function periodOrAllLabel(lang: Lang, year: string, quarter: string, month: string, week: string | null): string {
  const t = BOD_T[lang];
  const parts = [
    month ? `${month} ${year ?? ""}`.trim()
      : quarter ? `${quarter} ${year ?? ""}`.trim()
      : year ? String(year)
      : t.scopeAllPeriod,
    week || null,
  ].filter(Boolean);
  return parts.join(" · ");
}
